# Generated by scripts/create-package-manifests.mjs from the ijry/ai-switch release.
# Edit the generator, not this file: the next release overwrites it.
cask "ai-switch" do
  version "0.8.1"
  sha256 "f8741ed183a53b43bab63f1a4dca06de133abd1e60b97bd82034b94b8a9fb5b9"

  url "https://github.com/ijry/ai-switch/releases/download/v#{version}/ai-switch-#{version}-darwin-aarch64.dmg",
      verified: "github.com/ijry/ai-switch/"
  name "AI Switch"
  desc "Switch provider accounts and API routes for AI coding CLIs"
  homepage "https://ijry.github.io/ai-switch/"

  livecheck do
    url :url
    strategy :github_latest
  end

  # The app carries a Tauri updater that checks hourly and replaces its own
  # bundle, so what Homebrew recorded goes stale without Homebrew doing
  # anything. auto_updates is what keeps `brew upgrade` from fighting it.
  auto_updates true
  # Only Apple Silicon is built. No macos: floor is declared on purpose — every
  # arm64 Mac is already past it, and the version symbols Homebrew accepts get
  # pruned as releases go EOL. The bare :macos marks the cask macOS-only without
  # a floor: casks can target Linux now, so brew style's Homebrew/OSDependsOn
  # wants the OS said out loud. Both go in one stanza because the DSL takes the
  # OS positionally alongside the keyword arguments.
  depends_on :macos, arch: :arm64

  app "AI Switch.app"

  # CI builds macOS on an Apple Silicon runner with signingIdentity "-", so the
  # bundle is ad-hoc signed and never notarized. Gatekeeper answers a
  # quarantined ad-hoc bundle with "is damaged and can't be opened", which is
  # the dialog the install guide walks users through by hand. Clearing the flag
  # on the copy Homebrew just placed is what makes this a one-step install; it
  # touches that path only and changes no system-wide setting.
  #
  # must_succeed: false because xattr exits non-zero when the attribute is
  # already gone, and a Homebrew that did not quarantine the download must not
  # turn into a failed install.
  #
  # The padding after args: is what brew style wants: its Layout/HashAlignment is
  # configured for table style, so the values line up rather than the keys.
  postflight do
    system_command "/usr/bin/xattr",
                   args:         ["-dr", "com.apple.quarantine", "#{appdir}/AI Switch.app"],
                   must_succeed: false
  end

  # Credentials live in ~/.ai-switch, so this only ever runs for someone who
  # asked for `brew uninstall --zap`.
  zap trash: [
    "~/.ai-switch",
    "~/Library/Caches/io.xyito.ai-switch",
    "~/Library/HTTPStorages/io.xyito.ai-switch",
    "~/Library/Preferences/io.xyito.ai-switch.plist",
    "~/Library/Saved Application State/io.xyito.ai-switch.savedState",
    "~/Library/WebKit/io.xyito.ai-switch",
  ]
end
